### ISSUE TITLE
Converting code to be 2.0+ compatible

### ISSUE THREAD

**Issue by D3SL** [RinteRface/shinydashboardPlus#93]
While looking through the current reference manual online I noticed how many major breaking changes 2.0 is going to have. Are there any plans for an update guide, helper functions, deprecation warnings, or the like to aid in updating an app to work with 2.0? It would be nice as opposed to digging through the changelog and ctrl+f'ing everything under "breaking" to see if I've got it anywhere in my code.

**Comment by kaijagahm** [comment]
I'm also nervous about this. Commenting to follow.

**Comment by DivadNojnarg** [comment]
I suggest to use [`{renv}`](https://rstudio.github.io/renv/articles/renv.html) in your project(s) to capture the old version of `{shinydashboardPlus}`, thereby preventing them from breaking as soon as `{shinydashboardPlus}` 2.0.0 reaches CRAN. For new projects, you can depend on the new version. The `{renv}` workflow is fairly simple (copied and pasted from the doc):

- Call renv::init() to initialize a new project-local environment with a private R library,

- Work in the project as normal, installing and removing new R packages as they are needed in the project,

- Call renv::snapshot() to save the state of the project library to the lockfile (called renv.lock),

- Continue working on your project, installing and updating R packages as needed.

- Call renv::snapshot() again to save the state of your project library if your attempts to update R packages were successful, or call renv::restore() to revert to the previous state as encoded in the lockfile if your attempts to update packages introduced some new problems.

**Comment by kaijagahm** [comment]
@DivadNojnarg thank you for the suggestion! Unfortunately, because my organization uses a workflow that includes syncing with Box, it's not possible for me to use `renv` with my project (I gave a detailed account of the problems [here](https://community.rstudio.com/t/cant-load-package-lattice-which-causes-install-to-fail-for-geomorph/93122/10): basically Box doesn't allow syncing of certain files that are included in package folders). So I won't be able to use your suggestion, unfortunately.

Does the shinydashboardPlus team have an estimated timeline for putting the new version on CRAN? That would be useful to me in planning the transition.

Thank you!

**Comment by lmsimp** [comment]
Since 2.0.0 release, like many of your users, I have to completely re-write my Bioconductor package as all my apps used the earlier versions of `shinydashboardPlus`. Can I please ask if you are planning any further major re-writes as this will affect how and when to update my package. Thanks very much.

**Comment by DivadNojnarg** [comment]
This will not happen anymore:
- It was mainly to clean the bad code and bad design that accumulated during the past 2 years. 
- `{shinydashboard}` is a bit outdated (Bootstrap 3), while now Bootstrap 4/5 dashboards are available so there won't be any major update, except bug fixes ... and maybe some new features.

To answer @kaijagahm, if you can't use `{renv}` there is still the possibility to maintain an internal CRAN-like with custom package versions: for instance https://cran.r-project.org/web/packages/miniCRAN/vignettes/miniCRAN-introduction.html.
